# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eluka}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aditya Rachakonda"]
  s.date = %q{2010-12-17}
  s.description = %q{A LibSVM based support vector machine classifier for Ruby.}
  s.email = %q{aditya.rachakonda@gmail.com}
  s.extensions = ["ext/libsvm/extconf.rb", "ext/libsvm"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "DOCUMENTATION_STANDARDS",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "eluka.gemspec",
    "examples/example.rb",
    "ext/libsvm/COPYRIGHT",
    "ext/libsvm/FAQ.html",
    "ext/libsvm/Makefile",
    "ext/libsvm/Makefile.win",
    "ext/libsvm/README",
    "ext/libsvm/extconf.rb",
    "ext/libsvm/heart_scale",
    "ext/libsvm/java/Makefile",
    "ext/libsvm/java/libsvm.jar",
    "ext/libsvm/java/libsvm/svm.java",
    "ext/libsvm/java/libsvm/svm.m4",
    "ext/libsvm/java/libsvm/svm_model.java",
    "ext/libsvm/java/libsvm/svm_node.java",
    "ext/libsvm/java/libsvm/svm_parameter.java",
    "ext/libsvm/java/libsvm/svm_print_interface.java",
    "ext/libsvm/java/libsvm/svm_problem.java",
    "ext/libsvm/java/svm_predict.java",
    "ext/libsvm/java/svm_scale.java",
    "ext/libsvm/java/svm_toy.java",
    "ext/libsvm/java/svm_train.java",
    "ext/libsvm/java/test_applet.html",
    "ext/libsvm/python/Makefile",
    "ext/libsvm/python/README",
    "ext/libsvm/python/svm.py",
    "ext/libsvm/python/svmutil.py",
    "ext/libsvm/svm-predict.c",
    "ext/libsvm/svm-scale.c",
    "ext/libsvm/svm-toy/gtk/Makefile",
    "ext/libsvm/svm-toy/gtk/callbacks.cpp",
    "ext/libsvm/svm-toy/gtk/callbacks.h",
    "ext/libsvm/svm-toy/gtk/interface.c",
    "ext/libsvm/svm-toy/gtk/interface.h",
    "ext/libsvm/svm-toy/gtk/main.c",
    "ext/libsvm/svm-toy/gtk/svm-toy.glade",
    "ext/libsvm/svm-toy/qt/Makefile",
    "ext/libsvm/svm-toy/qt/svm-toy.cpp",
    "ext/libsvm/svm-toy/windows/svm-toy.cpp",
    "ext/libsvm/svm-train.c",
    "ext/libsvm/svm.cpp",
    "ext/libsvm/svm.def",
    "ext/libsvm/svm.h",
    "ext/libsvm/tools/README",
    "ext/libsvm/tools/checkdata.py",
    "ext/libsvm/tools/easy.py",
    "ext/libsvm/tools/grid.py",
    "ext/libsvm/tools/subset.py",
    "ext/libsvm/windows/libsvm.dll",
    "ext/libsvm/windows/svm-predict.exe",
    "ext/libsvm/windows/svm-scale.exe",
    "ext/libsvm/windows/svm-toy.exe",
    "ext/libsvm/windows/svm-train.exe",
    "lib/eluka.rb",
    "lib/eluka/bijection.rb",
    "lib/eluka/data_point.rb",
    "lib/eluka/document.rb",
    "lib/eluka/feature_vector.rb",
    "lib/eluka/features.rb",
    "lib/eluka/model.rb",
    "lib/fselect.rb",
    "lib/grid.rb",
    "test/helper.rb",
    "test/test_eluka.rb"
  ]
  s.homepage = %q{http://github.com/arrac/eluka}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A LibSVM based support vector machine classifier for Ruby.}
  s.test_files = [
    "examples/example.rb",
    "test/helper.rb",
    "test/test_eluka.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<ferret>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ferret>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ferret>, [">= 0"])
  end
end

